Delete tokens/main/0x93c92d2752e38154f41fdfa021fb4ba6fde49fa5 directory
vechain/token-registry pull request #104
Opened 2023-05-09 08:22 UTC by VetMaik

Delete this token because of total supply issue within vorj

2023-05-09 10:09 UTC, libotony commented
According to #98, testnet should also be removed

2023-05-10 09:48 UTC, libotony requested changes
According to https://github.com/vechain/token-registry/pull/98, testnet should also be removed

2023-05-11 14:53 UTC, VetMaik commented
Removed token from testnet

2023-05-12 03:22 UTC, libotony approved these changes

2023-05-12 03:22 UTC, merged