Add rain token
vechain/token-registry pull request #107
Opened 2023-05-13 02:36 UTC by ivardl

adding Rain token

2023-05-15 02:58 UTC, XJWX89 commented on tokens/main/0x3Cb62f48DBdC4f7627f37F027811565d292a1001/additional.json
> +  "website":"earth",
We do not currently accept this format.

2023-05-15 02:58 UTC, XJWX89 commented on tokens/test/0x3Cb62f48DBdC4f7627f37F027811565d292a1001/additional.json
> +  "website":"earth",
We do not currently accept this format.

2023-05-15 02:59 UTC, XJWX89 requested changes
hi @ivardl , Contract address start with 0x + 40 characters and **must be lower case**

2023-05-16 03:17 UTC, ivardl commented on tokens/main/0x3Cb62f48DBdC4f7627f37F027811565d292a1001/additional.json
> +  "website":"earth",
have updated with an actual website.

2023-05-16 03:22 UTC, ivardl commented
I made my folders all lowercase before the new commit but Im not sure this carried over. Please advise if I still did something wrong with the contract address structure.

2023-05-18 11:57 UTC, ivardl commented
@XJWX89 i did a commit deleting the old folders and another commit with new folders. Hopefully this resolves the folder name issue. Thank you.

2023-06-26 06:09 UTC, libotony approved these changes

2023-06-26 15:20 UTC, XJWX89 reviewed
hi @ivardl , sorry for the late reply. It seems that the contract address on mainnet and testnet are the same. if you do not have a contract on testnet ,You can simply provide the mainnet contract address.

2023-06-28 18:49 UTC, ivardl commented
Thanks for your patience. It looks like i may have changed more files than I intended. Please let me know if i broke anything. I think i deleted the testnet folder for rain. thank you.

2023-06-29 05:49 UTC, libotony commented
> Thanks for your patience. It looks like i may have changed more files than I intended. Please let me know if i broke anything. I think i deleted the testnet folder for rain. thank you.

Please do not delete other token's folder.

2023-08-13 23:58 UTC, closed without merging