New Memecoin for VeChain
vechain/token-registry pull request #120
Opened 2023-06-06 20:06 UTC by Murtagh300

2023-06-14 22:00 UTC, Murtagh300 commented
@XJWX89 Please look into this

2023-06-26 06:29 UTC, libotony requested changes

2023-06-26 06:29 UTC, libotony commented on tokens/main/0xb27a1fb87935b85cdaa2e16468247278c74c5ec7/additional.json
> +    "website":"No Website",
This line should be removed.

2023-06-26 06:29 UTC, libotony commented on tokens/test/0xcb384a3a82bfe0619963d65a05f3801ddc23f3cc/additional.json
> +    "website":"No Website",
This line should be removed.

2023-06-26 07:55 UTC, Murtagh300 commented
Should be fixxed now! @libotony

2023-06-26 08:02 UTC, libotony approved these changes

2023-06-26 08:07 UTC, libotony requested changes

2023-06-26 08:07 UTC, libotony commented on tokens/test/0xcb384a3a82bfe0619963d65a05f3801ddc23f3cc/Logo.png
This file should be named "logo.png"

2023-06-26 08:19 UTC, Murtagh300 commented
@libotony Changed both Logos in Correct logo.png Format

2023-06-26 08:25 UTC, libotony commented
> @libotony Changed both Logos in Correct logo.png Format

Sorry, I made a mistake, the name should be 'token.png'.

2023-06-26 09:29 UTC, Murtagh300 commented
Fixxed @libotony ❤️❤️

2023-06-26 09:39 UTC, libotony approved these changes

2023-06-27 06:49 UTC, merged