VSC and USDV token updated
vechain/token-registry pull request #122
Opened 2023-06-24 10:44 UTC by abinav124

Hi,
We have committed the VSC and USDV token into Vechain Mainnet.

2023-06-26 06:47 UTC, libotony requested changes

2023-06-26 06:47 UTC, libotony commented on tokens/main/0x094042f9719cd6736fa3bd45b605b1b2a23abdec/additional.json
> +  "whitePaper":""
This line should be removed.

2023-06-27 03:31 UTC, abinav124 commented on tokens/main/0x094042f9719cd6736fa3bd45b605b1b2a23abdec/additional.json
> +  "whitePaper":""
Those lines its removed

2023-06-27 03:32 UTC, abinav124 commented on tokens/main/0x094042f9719cd6736fa3bd45b605b1b2a23abdec/additional.json
> +  "whitePaper":""
committed ID [5265deb](https://github.com/vechain/token-registry/pull/122/commits/5265deb77577827f41528ee397709000390b2790)

2023-06-27 06:52 UTC, libotony requested changes

2023-06-27 06:52 UTC, libotony commented on tokens/main/0x65c542ad413dd406d7ae5e47f61fbda027ce7983/info
> +{
This file should be named `info.json`

2023-06-27 15:53 UTC, abinav124 commented on tokens/main/0x65c542ad413dd406d7ae5e47f61fbda027ce7983/info
> +{
The File name changed

2023-06-27 15:53 UTC, abinav124 commented on tokens/main/0x65c542ad413dd406d7ae5e47f61fbda027ce7983/info
> +{
Committed ID [cd568c4](https://github.com/vechain/token-registry/pull/122/commits/cd568c4412419018746829aa77298bb34b70df6d)

2023-06-28 03:17 UTC, libotony requested changes

2023-06-28 03:17 UTC, libotony commented on tokens/main/0x65c542ad413dd406d7ae5e47f61fbda027ce7983/additional.json
> +    "medium": "https://medium.com/@VyvoSmartChain",
```suggestion
    "medium": "https://medium.com/@VyvoSmartChain"
```

2023-06-28 03:38 UTC, abinav124 commented on tokens/main/0x65c542ad413dd406d7ae5e47f61fbda027ce7983/additional.json
> +    "medium": "https://medium.com/@VyvoSmartChain",
Its updated

2023-06-28 03:39 UTC, abinav124 commented on tokens/main/0x65c542ad413dd406d7ae5e47f61fbda027ce7983/additional.json
> +    "medium": "https://medium.com/@VyvoSmartChain",
Committed ID [6097df2](https://github.com/vechain/token-registry/pull/122/commits/6097df2f01e0eb723d523b36373b40c4fc46f305)

2023-06-28 04:39 UTC, libotony approved these changes

2023-06-28 16:36 UTC, XJWX89 approved these changes

2023-06-29 02:55 UTC, merged