Add Slayers Guild token SL4Y to VeChain token registry
vechain/token-registry pull request #160
Opened 2024-04-02 08:14 UTC by mrwhittleman

Adding Slayers Guild project token SL4Y to VeChain token registry.

2024-04-02 08:24 UTC, darrenvechain commented
@mrwhittleman 0x4B85757Bcf693f742003f2D5529CDc1672392F16 is not a contract on testnet. It looks like you copied and pasted from mainnet.

You can either deploy a contract and update the address, or remove the testnet contract

2024-04-02 08:29 UTC, mrwhittleman commented
> @mrwhittleman 0x4B85757Bcf693f742003f2D5529CDc1672392F16 is not a contract on testnet. It looks like you copied and pasted from mainnet.
> 
> You can either deploy a contract and update the address, or remove the testnet contract

I will remove the testnet contract!

2024-04-02 08:42 UTC, mrwhittleman commented
@darrenvechain All good?

2024-04-02 10:24 UTC, darrenvechain commented
@mrwhittleman I still see the testnet contract 
<img width="1474" alt="image" src="https://github.com/vechain/token-registry/assets/107671032/586edbb1-a5d9-41c8-b5a1-85a7c59f7d09">

2024-04-02 16:56 UTC, mrwhittleman commented
> @mrwhittleman I still see the testnet contract <img alt="image" width="1474" src="https://private-user-images.githubusercontent.com/107671032/318741551-586edbb1-a5d9-41c8-b5a1-85a7c59f7d09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzcyNjEsIm5iZiI6MTcxMjA3Njk2MSwicGF0aCI6Ii8xMDc2NzEwMzIvMzE4NzQxNTUxLTU4NmVkYmIxLWE1ZDktNDFjOC1iNWExLTg1YTdjNTlmN2QwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxNjU2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWZmNDNkNGE4OWM3ZGI0MTNkOTM2ZmUzODFmNzlhYmUzMmMzNzhjN2NjMmNlZWI5N2I5YjRhYmI3ZTZjNzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c6gkKqZJw37m-1EmDBdYItCBD9TFsJLCf1keTDHmxi4">

@darrenvechain Sorry about that. I thought I had deleted it before...

2024-04-03 17:31 UTC, mrwhittleman commented
@darrenvechain - Can you review and approve? Or let me know of any outstanding issues? Thank you!

2024-04-04 15:14 UTC, mrwhittleman commented on tokens/main/0x4b85757bcf693f742003f2d5529cdc1672392f16/additional.json
> +    "website":"https://www.slayersguild.io/",
We are working on the dApp currently. Should be up in a couple weeks. Our gitbook is already up https://docs.slayersguild.io

2024-04-04 16:11 UTC, mrwhittleman commented on tokens/main/0x4b85757bcf693f742003f2d5529cdc1672392f16/additional.json
> +    "website":"https://www.slayersguild.io/",
If that is unacceptable I can change the website to the docs.

2024-04-04 16:13 UTC, mrwhittleman commented
@libotony @darrenvechain updated additional .json to have website reflect our gitbook until dApp is up.

2024-04-09 09:59 UTC, libotony requested changes

2024-04-09 09:59 UTC, libotony commented on tokens/main/0x4b85757bcf693f742003f2d5529cdc1672392f16/additional.json
> +        "twitter":"https://twitter.com/vechainslayers",
```suggestion
        "twitter":"https://twitter.com/vechainslayers"
```

2024-04-10 08:53 UTC, libotony approved these changes

2024-04-10 09:46 UTC, merged