Cool Coin Registration pull request
vechain/token-registry pull request #163
Opened 2024-04-13 17:43 UTC by yothatscool

pull request for new token registry.

2024-04-17 14:22 UTC, libotony requested changes

2024-04-17 14:22 UTC, libotony commented on tokens/main/0x2f2220139e46bcc98273ecca2ded7bf56373b6cf/additional.json
> +      "twitter":"https://twitter.com/yothatscooldeux",
Please keep this and remove other examples.

2024-04-17 15:28 UTC, yothatscool commented on tokens/main/0x2f2220139e46bcc98273ecca2ded7bf56373b6cf/additional.json
> +      "twitter":"https://twitter.com/yothatscooldeux",
Thank you for checking this. I have removed the examples and kept the necessary information.

2024-04-17 19:15 UTC, yothatscool commented on tokens/main/0x2f2220139e46bcc98273ecca2ded7bf56373b6cf/additional.json
> +      "twitter":"https://twitter.com/yothatscooldeux",
of course... updated. Thank you!

2024-04-18 09:01 UTC, libotony commented
The image should be 256px * 256px

2024-04-25 10:49 UTC, libotony requested changes

2024-04-25 10:49 UTC, libotony commented on tokens/main/0x2f2220139e46bcc98273ecca2ded7bf56373b6cf/info.json
> +        "name": "COOL",
Message from the CI: name does not match contract name (info=COOL, contract=cool)

2024-04-25 14:02 UTC, libotony approved these changes

2024-04-25 14:02 UTC, merged