Add LlamaCoin
vechain/token-registry pull request #170
Opened 2024-08-09 07:06 UTC by DennisD076

2024-08-12 08:36 UTC, libotony requested changes

2024-08-12 08:36 UTC, libotony commented on tokens/main/0x8cE14e9906C64F8e17fA27eb51d3Db1df3DA2c16/additional.json
> +{
Folder should be the address in lower case, please update accordingly.

2024-08-12 09:04 UTC, DennisD076 commented
address is added in lower case. Thanks!

2024-08-20 10:11 UTC, libotony commented
@DennisD076  Image should be 256px * 256px

2024-08-21 07:19 UTC, libotony approved these changes

2024-08-21 07:43 UTC, libotony commented
Info from script, name does not match contract name (info=LlamaCoin, contract=LLAMACOIN).

2024-08-21 09:36 UTC, libotony commented
Info from script, symbol does not match contract symbol (info=LLAMA, contract=LLAMACOIN).

2024-08-21 09:37 UTC, libotony commented
> Info from script, symbol does not match contract symbol (info=LLAMA, contract=LLAMACOIN).

I think `LLAMA` is the right symbol, correct? @DennisD076, But it seems to be not correctly configured at the contract level.

2024-08-21 09:49 UTC, DennisD076 commented
I deployed the SC with LLAMACOIN symbol aswell, keep it that way please

2024-08-21 09:50 UTC, DennisD076 commented
Not adjustable anymore

2024-08-26 10:05 UTC, merged