change SHA token address on TESTNET
vechain/token-registry pull request #29
Opened 2020-08-27 21:58 UTC by JurgenSchouppe

2020-08-28 04:18 UTC, libotony commented
@JurgenSchouppe are you planing changing the address on mainnet?

2020-08-28 07:36 UTC, Zds23gbo commented
Здравствуйте я только учусь работать с криптой, если это угрожает или вредит сети, приостоновите пожалуйста. Спасибо большое

2020-08-28 07:42 UTC, Zds23gbo requested changes
Я не могу точно ответить на вопрос. Если вы хотите изменить и не повредит узлу прошу вас продолжить. Спасибо большое

2020-08-28 16:26 UTC, JurgenSchouppe commented
no, only on testnet

kind regards 

jürgen 

> On 28 Aug 2020, at 06:18, libotony <notifications@github.com> wrote:
> 
> ﻿
> @JurgenSchouppe are you planing changing the address on mainnet?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-28 16:31 UTC, Zds23gbo commented
Здравствуйте, хорошо я буду экспериментировать в тестовой сети. Спасибо большое
Если вас не затруднит поглядывайте за мной чтобы я что нибудь не испортил.

2020-08-29 06:11 UTC, libotony commented
> no, only on testnet kind regards jürgen
> […](#)
> On 28 Aug 2020, at 06:18, libotony ***@***.***> wrote: ﻿ @JurgenSchouppe are you planing changing the address on mainnet? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Got it, please be noted that after merging this PR, we will update our explorer the **OLD** SHA token will no longer be shown in the explorer(token detail, token transfer) instead of the new contract. And mytoken app will not be able to transfer **OLD** SHA token.

2020-09-04 02:43 UTC, libotony approved these changes

2020-09-04 02:43 UTC, merged

2020-09-04 03:06 UTC, Zds23gbo commented
Спасибо большое, в данный период мы строим себе дом и убираем урожай в огороде, до компьютера дойти сил не хватает, как немного освобожусь займусь компьютером,  если Вас не затруднит посмотрите пожалуйста я буду очень признателен. Спасибо большое