add mvg token
vechain/token-registry pull request #48
Opened 2021-09-14 11:51 UTC by DanielDonosoRasmussen

2021-09-15 07:30 UTC, XJWX89 commented on tokens/main/0x99763494a7b545f983ee9fe02a3b5441c7ef1396/additional.json
> +    "medium":"https://medium.com/@MadVikingGames,
should be `"medium":"https://medium.com/@MadVikingGames"`

2021-09-15 07:31 UTC, XJWX89 commented on tokens/test/0x6e32a40481dc95c7495b48ee81e3d388a0f0eb77/additional.json
> +    "medium":"https://medium.com/@MadVikingGames,
should be `"medium":"https://medium.com/@MadVikingGames"`

2021-09-16 05:21 UTC, libotony requested changes
This PR did not pass the CI system's validation, please take a look at [detail](https://github.com/vechain/token-registry/pull/48/checks?check_run_id=3617507677). You can run the validation script before committing by `npm run build`

2021-09-18 02:37 UTC, XJWX89 approved these changes

2021-09-18 03:07 UTC, libotony approved these changes

2021-09-18 03:07 UTC, merged

2022-03-01 05:57 UTC, Moejojojojo commented on tokens/main/0x99763494a7b545f983ee9fe02a3b5441c7ef1396/additional.json
> +    "medium":"https://medium.com/@MadVikingGames,
diff --git a/Rakefile b/Rakefile
new file mode 100644
index 0000000000..413341f4cf
--- /dev/null
+++ b/Rakefile
@@ -0,0 +1,13 @@
+repository_dispatch/WORKSFLOW/GETEVENTLISTNER/TOGGLE-ON:AUTOMATES::ALL: EVENTS:rRun::/Runs:
+:Build:: Nane
+Name: Repository Dispatch
+        uses: peter-evans/repository-dispatch@v1
+        with:
+          token: ${{ secrets.REPO_ACCESS_TOKEN }}
+          repository: username/my-repo
+          event-type: my-event
+          client-payload: '{"ref": "${{ github.ref }}"}"''Zachry Tyler Wood
+5323 BRADFORD DRIVE
+DALLAS TX 75235-8313
+Bitcoin[BTC-USD] BTCUSD CCC
+o'Auth: **approves**