Feature/wov token application
vechain/token-registry pull request #50
Opened 2021-09-20 07:51 UTC by m-spoke

2021-09-20 10:26 UTC, Zds23gbo approved these changes

2021-09-22 07:20 UTC, XJWX89 requested changes
folder name(contract address) must be lower case

2021-09-22 07:43 UTC, Zds23gbo approved these changes

2021-09-23 10:22 UTC, XJWX89 approved these changes

2021-09-24 10:00 UTC, merged