Add DRAGON token
vechain/token-registry pull request #72
Opened 2022-05-15 18:27 UTC by Scale0

The main currency used For Staking and evolving your Dragon egg. Dragons of Singapura. Will also be used for future nft drops within Singapura

2022-05-16 03:06 UTC, XJWX89 requested changes

2022-05-16 03:06 UTC, XJWX89 commented on tokens/main/0x107a0b0faeb58c1fdef97f37f50e319833ad1b94/info.json
> +    "name": "Dragon Coins",
according to the contract, it should be `Dragon Coin` instead of `Dragon Coins`

2022-05-16 03:06 UTC, XJWX89 commented on tokens/test/0x98ceed8ee645c2d964cc0dd4342c832d52aeeb13/info.json
> +    "name": "Dragon Coins",
according to the contract, it should be Dragon Coin instead of Dragon Coins

2022-05-16 08:16 UTC, Scale0 commented
@XJWX89 fixxed :)

2022-05-16 08:56 UTC, XJWX89 approved these changes

2022-05-26 09:02 UTC, Murtagh300 commented
Can we get it merged Before mint ?

We would like to distribute straight after.

Dragons of Singapura 

Pre sale start 28th of may
Public sale 29th of may 

Dapp PR is on his way.

2022-05-26 09:04 UTC, merged

2022-05-26 09:22 UTC, Murtagh300 commented
That was quick Thankyou !