Add 3DT token
vechain/token-registry pull request #99
Opened 2023-04-21 20:50 UTC by Emilvooo

Adding 3DAble token

2023-05-04 02:32 UTC, XJWX89 commented on tokens/test/0x5799543e3e0e0e89e5e917e2676d66b23013a654/info.json
> +  "symbol": "3DT",
I have checked and found that the symbol provided does not match the information provided.

2023-05-04 02:32 UTC, XJWX89 commented on tokens/test/0x5799543e3e0e0e89e5e917e2676d66b23013a654/info.json
> +  "name": "3DAble Token",
I have checked and found that the symbol provided does not match the information provided.  it should be `ThreeDAbleToken `

2023-05-04 02:32 UTC, XJWX89 commented on tokens/main/0x8fcddbb322b18d8bdaec9243e9f4c6eb8901e566/info.json
> +  "name": "3DAble Token",
I have checked and found that the symbol provided does not match the information provided.  it should be `ThreeDAbleToken `

2023-05-04 02:36 UTC, XJWX89 requested changes
hi @Emilvooo ,I have found some issues in the data you provided. Please check and make the necessary changes. If you have any further questions, please feel free to ask

2023-05-16 21:24 UTC, Emilvooo commented
@XJWX89 Thanks, changed it :)

2023-05-30 19:58 UTC, Emilvooo commented
@libotony @XJWX89 could you check in on this? Thanks!

2023-05-31 13:42 UTC, libotony commented on tokens/test/0x5799543e3e0e0e89e5e917e2676d66b23013a654/info.json
> +  "symbol": "TDT",
The token symbol on testnet is `TDT`, as `3DT` on mainnet. But they share the same name and image, could you elaborate?

2023-06-02 13:24 UTC, Emilvooo commented on tokens/test/0x5799543e3e0e0e89e5e917e2676d66b23013a654/info.json
> +  "symbol": "TDT",
The contract on mainnet was deployed later on, where we decided to change the symbol :)

2023-06-26 03:33 UTC, libotony commented on tokens/test/0x5799543e3e0e0e89e5e917e2676d66b23013a654/info.json
> +  "symbol": "TDT",
Our recommendation is to keep the token symbol consistent between the mainnet and testnet. Please let us know if this aligns with your preferences.

2023-06-26 06:04 UTC, Emilvooo commented
@libotony Changed testnet contract to be in line with mainnet. Let me know if this is correct now.

2023-06-26 06:13 UTC, libotony commented
> @libotony Changed testnet contract to be in line with mainnet. Let me know if this is correct now.

Thanks, looking good now

2023-06-26 06:21 UTC, libotony approved these changes

2023-06-26 15:10 UTC, XJWX89 approved these changes

2023-06-27 06:43 UTC, merged